language: java

jdk:
  - oraclejdk8

after_success:
  - echo $TRAVIS_BRANCH
  
branches:
  only:
    - dev
    - master

deploy:
  provider: script
  script: bash branchworks.sh
  on:
    branch: dev
